version: "3.9"

services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qa-tests
    working_dir: /app

    command: dotnet test

    volumes:
      - ./allure-results:/app/bin/Debug/net8.0/allure-results
    shm_size: "2gb"